# Generated by Django 5.1.6 on 2025-03-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_profile_balance_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='history_received',
            new_name='coinHistory',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='history_sent',
        ),
    ]
