# Generated by Django 5.1.6 on 2025-03-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='inventory',
            field=models.TextField(default='{}'),
        ),
    ]
