# Generated by Django 5.1.6 on 2025-03-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='history_received',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='history_sent',
            field=models.TextField(default='{}'),
        ),
    ]
