# Generated by Django 5.1.6 on 2025-03-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userprofile_history_received_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='history_received',
            new_name='history',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='history_sent',
        ),
    ]
