# Generated by Django 5.1.6 on 2025-03-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_history_received_userprofile_history_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='history',
            new_name='coinHistory',
        ),
    ]
