# Generated by Django 5.1.6 on 2025-03-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_history_userprofile_coinhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='coinHistory',
            field=models.TextField(default='{}'),
        ),
    ]
